/**
 * Eufy robot error codes (ErrorCode.error, dp 177), from eufy-clean's
 * EUFY_CLEAN_ERROR_CODES. Only the top-level codes are kept; the four-digit
 * motor diagnostics fall back to the bare number.
 */
export const EUFY_ERROR_DESCRIPTIONS: Readonly<Record<number, string>> = {
  1: 'Bumper stuck',
  2: 'Wheel stuck',
  3: 'Side brush stuck',
  4: 'Rolling brush stuck',
  5: 'Trapped, clear the obstacle',
  6: 'Trapped, move the robot',
  7: 'Wheel overhanging',
  8: 'Battery too low, shut down',
  13: 'Robot tilted',
  14: 'Dust box missing',
  17: 'Forbidden area detected',
  18: 'Laser cover stuck',
  19: 'Laser sensor stuck',
  20: 'Laser blocked',
  21: 'Failed to dock',
  26: 'Scheduled clean failed to start',
  31: 'Suction port blocked',
  32: 'Wipe holder motor stuck',
  33: 'Wiping bracket motor stuck',
  39: 'Positioning failed, clean ended',
  40: 'Mop cloth dislodged',
  41: 'Air dryer heater abnormal',
  50: 'Robot is on carpet',
  51: 'Camera blocked',
  52: 'Unable to leave the station',
  55: 'Could not find the station',
  70: 'Clean the dust collector',
  71: 'Wall sensor failed',
  72: 'Robot water low',
  73: 'Dirty water tank full',
  74: 'Clean water low',
  75: 'Water tank missing',
  76: 'Camera abnormal',
  77: '3D ToF sensor abnormal',
  78: 'Ultrasonic sensor abnormal',
  79: 'Cleaning tray not installed',
  80: 'Robot communication failed',
  81: 'Sewage tank leaking',
  82: 'Cleaning tray needs cleaning',
  83: 'Poor charging contact',
  101: 'Battery abnormal',
  102: 'Wheel module abnormal',
  103: 'Side brush abnormal',
  104: 'Fan abnormal',
  105: 'Roller brush motor abnormal',
  106: 'Pump abnormal',
  107: 'Laser sensor abnormal',
  111: 'Rotation motor abnormal',
  112: 'Lift motor abnormal',
  113: 'Water spray abnormal',
  114: 'Water pump abnormal',
  117: 'Ultrasonic sensor abnormal',
  119: 'Wi-Fi/Bluetooth abnormal',
};

export function describeEufyError(code: number): string {
  return EUFY_ERROR_DESCRIPTIONS[code] ?? `Eufy error ${code}`;
}
